# Generated by Django 3.1.6 on 2021-02-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
